apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static
  name: static
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 1000
    image: busybox
    name: static
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
