---
- name: Debug
  hosts: localhost
  # become: true
  # become_user: abracadabra

  tasks:

    - name: Get current user.
      ansible.builtin.command: >
        whoami
      register: whoami_result
      changed_when: false

    - name: Display current host and current user.
      ansible.builtin.debug:
        msg:
          - Running on host={{ inventory_hostname }} with user={{ whoami_result.stdout }}
          - ansible_distribution_major_version == "{{ ansible_distribution_major_version }}"
