apiVersion: v1
kind: Service
metadata:
  name: prometheus-stack-grafana-lb
  namespace: monitoring
spec:
  ports:
  - name: http-web
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
